# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190719_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/account/%Y/%m/%d'),
        ),
    ]
